name: Performance Tests

on:
  schedule:
    - cron: '0 2 * * *'  # Run daily at 2 AM
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Target URL for performance testing'
        required: true
        default: 'https://staging.sfmc-dev-suite.com'
      duration:
        description: 'Test duration in minutes'
        required: false
        default: '5'
        type: string

env:
  NODE_VERSION: '18'

jobs:
  performance-test:
    name: Run Performance Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install k6
      run: |
        sudo gpg -k
        sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
        echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
        sudo apt-get update
        sudo apt-get install k6

    - name: Run load tests
      run: |
        TARGET_URL="${{ github.event.inputs.target_url || 'https://staging.sfmc-dev-suite.com' }}"
        DURATION="${{ github.event.inputs.duration || '5' }}"
        
        k6 run --duration="${DURATION}m" --vus=10 \
          --env TARGET_URL="$TARGET_URL" \
          scripts/performance/load-test.js

    - name: Run stress tests
      run: |
        TARGET_URL="${{ github.event.inputs.target_url || 'https://staging.sfmc-dev-suite.com' }}"
        
        k6 run --duration=2m --vus=50 \
          --env TARGET_URL="$TARGET_URL" \
          scripts/performance/stress-test.js

    - name: Run spike tests
      run: |
        TARGET_URL="${{ github.event.inputs.target_url || 'https://staging.sfmc-dev-suite.com' }}"
        
        k6 run --duration=3m \
          --env TARGET_URL="$TARGET_URL" \
          scripts/performance/spike-test.js

    - name: Upload performance results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: performance-results
        path: |
          performance-results.json
          *.html
        retention-days: 30

    - name: Comment performance results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          if (fs.existsSync('performance-results.json')) {
            const results = JSON.parse(fs.readFileSync('performance-results.json', 'utf8'));
            const comment = `## Performance Test Results
            
            | Metric | Value |
            |--------|-------|
            | Average Response Time | ${results.avg_response_time}ms |
            | 95th Percentile | ${results.p95_response_time}ms |
            | Requests/sec | ${results.requests_per_sec} |
            | Error Rate | ${results.error_rate}% |
            
            Full results available in the artifacts.`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
          }